DEV = process.env.NODE_ENV isnt 'production'
PRODUCTION = not DEV

ROOT_STATIC_FILES = [
    'robots.txt'
    'favicon.ico'
    'sitemap.xml'
]
{
    API_PATH
    AUTH_TOKEN_COOKIE_KEY
    AUTH_TOKEN_EXPIRATION_DAYS
    DB_URL
    GRAPHQL_PATH
    GRAPHIQL_PATH
    STATIC_PATH
} = process.env

AUTH_TOKEN_EXPIRATION_DAYS = parseInt(AUTH_TOKEN_EXPIRATION_DAYS)

module.exports = {
    API_PATH
    AUTH_TOKEN_COOKIE_KEY
    AUTH_TOKEN_EXPIRATION_DAYS
    DB_URL
    DEV
    GRAPHQL_PATH
    GRAPHIQL_PATH
    PRODUCTION
    ROOT_STATIC_FILES
    STATIC_PATH
}
